### ISSUE TITLE
FoodCheck#20: Testing de acceso a modalidades premium

### ISSUE THREAD

**Issue by chemaccs** [ispp-FoodCheck/FoodCheck#151]
- Comprobar que puedes hacerte **premium** (**Comprobar la pasarela de pago**).
- Comprobar que siendo **premium** puedo acceder a las funcionalidades extra.
- Comprobar que si no eres **premium** no tienes estas funcionalidades (**Incluye comprobar que solo se puede desbloquear una receta**).

**Comment by migueegomez7** [comment]
La de poner un disclaimer que hay que usar el mismo correo en la pasarela con el que estás registrao en FoodCheck sería un detalle
