### ISSUE TITLE
FoodCheck #13: Añadir estilo al html

### ISSUE THREAD

**Issue by migueegomez7** [ispp-FoodCheck/FoodCheck#34]
Empleando bootstrap, se deberá dar estilo a las diferentes vistas de la aplicación, teniendo como base el mockup. Además deberá ser responsive.

**Comment by xiscomigueles** [comment]
Dado el feedback del sprint 1, en Listar productos podeis hacer la funcionalidad esta que la pide muchos usuarios y es sobre la estettica visual de la pagina:
- Elementos del mismo tamaño (maneter simetría) y diseño de la cajas más agradable con colores de más contraste.
